version: "3"
services:
  db-banque:
    container_name: db-banque
    image: postgres:13
    volumes:
      - ./database/init-banque.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  db-magasin:
    container_name: db-magasin
    image: postgres:13
    volumes:
      - ./database/init-magasin.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db